### ISSUE TITLE
Some pulsars apparently not on databse

### ISSUE THREAD

**Issue by keegansmith21** [NickSwainston/mwa_search#26]
The catalogue used by prepfold is not exactly the same as the psrcat catalogue we're using. This sometimes leads to prefold failing because it can't find the pulsar we're referencing. What's more frustrating is that this exits with errorcode 0, so the script can't be automatically terminated and it just keeps relaunching endlessly. Don't know how to fix it yet...

**Comment by NickSwainston** [comment]
So if you use -timing it should use the eph that you get from psrcat so I assume you're talking about when that fails and we use the -psr option which is definitely a hot mess and we should try not to use.

I'm confused why it's looping endlessly. Do you mean the error code is non-zero or is there something in your code that keeps going until a new bin is made

**Comment by keegansmith21** [comment]
No this is even after trying the -timing option. The error says something along the lines of "pulsar not on databse" and is spit out by prepfold. 

The looping occurs because this doesn't result in a non-zero errorcode, which means my script doesn't terminate, then it looks in the same directory and sees the same files and tries the exact same thing again.

**Comment by NickSwainston** [comment]
I assume we fixed this
